### ISSUE TITLE
CM status for i9210t

### ISSUE THREAD

**Issue by c42f** [Talustus/android_device_samsung_i9210t#1]
Hey I've just been given an old GT-i9210t which I'd like to upgrade with a recent cyanogenmod.  This is mainly due to security concerns with the stock ROM, given various security issues which keep coming up with old android versions.

I've looked around on the web for a summary of the status of CM on the i9210t and found some insanely long threads on xda-developers, but it's hard to find anything recent and definitive.  I've got the skills to hack something up myself (and contribute any updates here or elsewhere as appropriate), but I really want to build on someone else's work since I don't have a heap of time for it.

Do you have a summary of the current state of CM on i9210t?  Is this the repo I should be contributing to if I was to fix things?  Any idea of how much effort it's likely to be to get CM12 running on this device?  Point of reference: I've got a fair bit of low level reverse engineering experience, but I'm an android noob at this point.

**Comment by nutterpc** [comment]
Some of the better ROMS which I also used for the i9210T when I had
mine, was the following:

http://forum.xda-developers.com/showpost.php?p=31319717&postcount=495&nocache=1

That's the thread which we all worked together on. I also did my own S2
4G Kernel, which altho abandoned, I'm looking at reviving possibly

Feel free to ask any other questions if you need

**Comment by c42f** [comment]
Awesome, thanks!  If that's the definitive thread I should try reading through to see the problems that came up and were solved so far.  Will give that a go, though it's pretty epic at 200 pages.  I guess most devs who care have probably moved on from the S2 to newer phones..

**Comment by nutterpc** [comment]
For the S2 4G it's basically _the_ thread. The only 2 devs who were
regularly contributing to it were myself and Talustus

**Comment by c42f** [comment]
Are there any parts you'd suggest reading first, or just start at the beginning?

**Comment by Talustus** [comment]
@c42f feel free to drop by into our IRC channel  (Server: irc.dream-irc.com - Channel: #teamskyfire ) to get the downloads for GT-I9210T (cm) there is a Download Bot available wich still holds some of the known to work properly CM builds. they are maybe not the newest but working well. So far i stoped development for the I9210T as it realy reached its "EOL" but the builds on the bot still provide a good dayly driver to use if u have further questions ask on the IRC channel (u may need to be patient as i'm not online all the day) but i read the messages when i get online ....

Also if u want to continue the work on the GT-I9210t feel free to fork this REPO it is used to build all the CM-Builds, if u commit fixes u can create pull requests wich i will merge for future forks etc ...

best regards

**Comment by c42f** [comment]
Thanks, I did wonder if any binaries were still available.  If I get to it I'll probably build it myself but it's good to have the binaries as an option.  I must admit some apathy has set in after reading a lot and realizing how relatively obscure the i9210T is, and how any effort poured into this more-or-less EOL phone is unlikely to translate to any other model...

**Comment by Talustus** [comment]
still even if the GT-I9210T reached it EOL its still a decent device/hardware and it ist not a waste of time to build for it in my mind ...
i just went out of time to maintain it so far.
So if u like feel free to build for it i'm sure u would get some benefits from it
